# Generated by Django 4.0.3 on 2022-10-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_region_alter_estate_options_estate_floor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Название районов', 'verbose_name_plural': 'Название районов'},
        ),
        migrations.AddField(
            model_name='estate',
            name='price',
            field=models.FloatField(default=1, max_length=255, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
